package group

type SymbolObject struct {
	Path                           string `json:"Path"`
	TradeMode                      string `json:"TradeMode"`
	ExecMode                       string `json:"ExecMode"`
	FillFlags                      string `json:"FillFlags"`
	ExpirFlags                     string `json:"ExpirFlags"`
	OrderFlags                     string `json:"OrderFlags"`
	SpreadDiff                     string `json:"SpreadDiff"`
	SpreadDiffBalance              string `json:"SpreadDiffBalance"`
	StopsLevel                     string `json:"StopsLevel"`
	FreezeLevel                    string `json:"FreezeLevel"`
	VolumeMin                      string `json:"VolumeMin"`
	VolumeMinExt                   string `json:"VolumeMinExt"`
	VolumeMax                      string `json:"VolumeMax"`
	VolumeMaxExt                   string `json:"VolumeMaxExt"`
	VolumeStep                     string `json:"VolumeStep"`
	VolumeStepExt                  string `json:"VolumeStepExt"`
	VolumeLimit                    string `json:"VolumeLimit"`
	VolumeLimitExt                 string `json:"VolumeLimitExt"`
	MarginFlags                    string `json:"MarginFlags"`
	MarginInitial                  string `json:"MarginInitial"`
	MarginMaintenance              string `json:"MarginMaintenance"`
	MarginInitialBuy               string `json:"MarginInitialBuy"`
	MarginInitialSell              string `json:"MarginInitialSell"`
	MarginInitialBuyLimit          string `json:"MarginInitialBuyLimit"`
	MarginInitialSellLimit         string `json:"MarginInitialSellLimit"`
	MarginInitialBuyStop           string `json:"MarginInitialBuyStop"`
	MarginInitialSellStop          string `json:"MarginInitialSellStop"`
	MarginInitialBuyStopLimit      string `json:"MarginInitialBuyStopLimit"`
	MarginInitialSellStopLimit     string `json:"MarginInitialSellStopLimit"`
	MarginMaintenanceBuy           string `json:"MarginMaintenanceBuy"`
	MarginMaintenanceSell          string `json:"MarginMaintenanceSell"`
	MarginMaintenanceBuyLimit      string `json:"MarginMaintenanceBuyLimit"`
	MarginMaintenanceSellLimit     string `json:"MarginMaintenanceSellLimit"`
	MarginMaintenanceBuyStop       string `json:"MarginMaintenanceBuyStop"`
	MarginMaintenanceSellStop      string `json:"MarginMaintenanceSellStop"`
	MarginMaintenanceBuyStopLimit  string `json:"MarginMaintenanceBuyStopLimit"`
	MarginMaintenanceSellStopLimit string `json:"MarginMaintenanceSellStopLimit"`
	MarginLiquidity                string `json:"MarginLiquidity"`
	MarginHedged                   string `json:"MarginHedged"`
	MarginCurrency                 string `json:"MarginCurrency"`
	SwapMode                       string `json:"SwapMode"`
	SwapLong                       string `json:"SwapLong"`
	SwapShort                      string `json:"SwapShort"`
	Swap3Day                       string `json:"Swap3Day"`
	SwapYearDay                    string `json:"SwapYearDay"`
	REFlags                        string `json:"REFlags"`
	RETimeout                      string `json:"RETimeout"`
	IEFlags                        string `json:"IEFlags"`
	IECheckMode                    string `json:"IECheckMode"`
	IETimeout                      string `json:"IETimeout"`
	IESlipProfit                   string `json:"IESlipProfit"`
	IESlipLosing                   string `json:"IESlipLosing"`
	IEVolumeMax                    string `json:"IEVolumeMax"`
	IEVolumeMaxExt                 string `json:"IEVolumeMaxExt"`
	PermissionsFlags               string `json:"PermissionsFlags"`
	PermissionsBookdepth           string `json:"PermissionsBookdepth"`
}
