package symbol

type SymbolObject struct {
	Symbol                         string `json:"Symbol"`
	Path                           string `json:"Path"`
	ISIN                           string `json:"ISIN"`
	CFI                            string `json:"CFI"`
	Category                       string `json:"Category"`
	Exchange                       string `json:"Exchange"`
	Description                    string `json:"Description"`
	International                  string `json:"International"`
	Sector                         string `json:"Sector"`
	Industry                       string `json:"Industry"`
	Country                        string `json:"Country"`
	Basis                          string `json:"Basis"`
	Source                         string `json:"Source"`
	Page                           string `json:"Page"`
	CurrencyBase                   string `json:"CurrencyBase"`
	CurrencyBaseDigits             string `json:"CurrencyBaseDigits"`
	CurrencyProfit                 string `json:"CurrencyProfit"`
	CurrencyProfitDigits           string `json:"CurrencyProfitDigits"`
	CurrencyMargin                 string `json:"CurrencyMargin"`
	CurrencyMarginDigits           string `json:"CurrencyMarginDigits"`
	Color                          string `json:"Color"`
	ColorBackground                string `json:"ColorBackground"`
	Digits                         string `json:"Digits"`
	Point                          string `json:"Point"`
	Multiply                       string `json:"Multiply"`
	TickFlags                      string `json:"TickFlags"`
	TickBookDepth                  string `json:"TickBookDepth"`
	TickChartMode                  string `json:"TickChartMode"`
	SubscriptionsDelay             string `json:"SubscriptionsDelay"`
	FilterSoft                     string `json:"FilterSoft"`
	FilterSoftTicks                string `json:"FilterSoftTicks"`
	FilterHard                     string `json:"FilterHard"`
	FilterHardTicks                string `json:"FilterHardTicks"`
	FilterDiscard                  string `json:"FilterDiscard"`
	FilterSpreadMax                string `json:"FilterSpreadMax"`
	FilterSpreadMin                string `json:"FilterSpreadMin"`
	FilterGap                      string `json:"FilterGap"`
	FilterGapTicks                 string `json:"FilterGapTicks"`
	TradeMode                      string `json:"TradeMode"`
	TradeFlags                     string `json:"TradeFlags"`
	CalcMode                       string `json:"CalcMode"`
	ExecMode                       string `json:"ExecMode"`
	GTCMode                        string `json:"GTCMode"`
	FillFlags                      string `json:"FillFlags"`
	ExpirFlags                     string `json:"ExpirFlags"`
	OrderFlags                     string `json:"OrderFlags"`
	Spread                         string `json:"Spread"`
	SpreadBalance                  string `json:"SpreadBalance"`
	SpreadDiff                     string `json:"SpreadDiff"`
	SpreadDiffBalance              string `json:"SpreadDiffBalance"`
	TickValue                      string `json:"TickValue"`
	TickSize                       string `json:"TickSize"`
	ContractSize                   string `json:"ContractSize"`
	StopsLevel                     string `json:"StopsLevel"`
	FreezeLevel                    string `json:"FreezeLevel"`
	QuotesTimeout                  string `json:"QuotesTimeout"`
	VolumeMin                      string `json:"VolumeMin"`
	VolumeMinExt                   string `json:"VolumeMinExt"`
	VolumeMax                      string `json:"VolumeMax"`
	VolumeMaxExt                   string `json:"VolumeMaxExt"`
	VolumeStep                     string `json:"VolumeStep"`
	VolumeStepExt                  string `json:"VolumeStepExt"`
	VolumeLimit                    string `json:"VolumeLimit"`
	VolumeLimitExt                 string `json:"VolumeLimitExt"`
	MarginFlags                    string `json:"MarginFlags"`
	MarginInitial                  string `json:"MarginInitial"`
	MarginMaintenance              string `json:"MarginMaintenance"`
	MarginInitialBuy               string `json:"MarginInitialBuy"`
	MarginInitialSell              string `json:"MarginInitialSell"`
	MarginInitialBuyLimit          string `json:"MarginInitialBuyLimit"`
	MarginInitialSellLimit         string `json:"MarginInitialSellLimit"`
	MarginInitialBuyStop           string `json:"MarginInitialBuyStop"`
	MarginInitialSellStop          string `json:"MarginInitialSellStop"`
	MarginInitialBuyStopLimit      string `json:"MarginInitialBuyStopLimit"`
	MarginInitialSellStopLimit     string `json:"MarginInitialSellStopLimit"`
	MarginMaintenanceBuy           string `json:"MarginMaintenanceBuy"`
	MarginMaintenanceSell          string `json:"MarginMaintenanceSell"`
	MarginMaintenanceBuyLimit      string `json:"MarginMaintenanceBuyLimit"`
	MarginMaintenanceSellLimit     string `json:"MarginMaintenanceSellLimit"`
	MarginMaintenanceBuyStop       string `json:"MarginMaintenanceBuyStop"`
	MarginMaintenanceSellStop      string `json:"MarginMaintenanceSellStop"`
	MarginMaintenanceBuyStopLimit  string `json:"MarginMaintenanceBuyStopLimit"`
	MarginMaintenanceSellStopLimit string `json:"MarginMaintenanceSellStopLimit"`
	MarginLiquidity                string `json:"MarginLiquidity"`
	MarginHedged                   string `json:"MarginHedged"`
	MarginCurrency                 string `json:"MarginCurrency"`
	SwapMode                       string `json:"SwapMode"`
	SwapLong                       string `json:"SwapLong"`
	SwapShort                      string `json:"SwapShort"`
	Swap3Day                       string `json:"Swap3Day"`
	SwapYearDay                    string `json:"SwapYearDay"`
	TimeStart                      string `json:"TimeStart"`
	TimeExpiration                 string `json:"TimeExpiration"`
	SessionsQuotes                 [][]struct {
		Open  string `json:"Open"`
		Close string `json:"Close"`
	} `json:"SessionsQuotes"`
	SessionsTrades [][]struct {
		Open  string `json:"Open"`
		Close string `json:"Close"`
	} `json:"SessionsTrades"`
	REFlags         string `json:"REFlags"`
	RETimeout       string `json:"RETimeout"`
	IECheckMode     string `json:"IECheckMode"`
	IETimeout       string `json:"IETimeout"`
	IESlipProfit    string `json:"IESlipProfit"`
	IESlipLosing    string `json:"IESlipLosing"`
	IEVolumeMax     string `json:"IEVolumeMax"`
	IEVolumeMaxExt  string `json:"IEVolumeMaxExt"`
	PriceSettle     string `json:"PriceSettle"`
	PriceLimitMax   string `json:"PriceLimitMax"`
	PriceLimitMin   string `json:"PriceLimitMin"`
	PriceStrike     string `json:"PriceStrike"`
	OptionMode      string `json:"OptionMode"`
	FaceValue       string `json:"FaceValue"`
	AccruedInterest string `json:"AccruedInterest"`
	SpliceType      string `json:"SpliceType"`
	SpliceTimeType  string `json:"SpliceTimeType"`
	SpliceTimeDays  string `json:"SpliceTimeDays"`
}
